resolver: lts-20.26
packages:
  - .
extra-deps:
  - Cabal-3.6.3.0
  - semver-range-0.2.8
  - fsnotify-0.4.1.0
  - versions-5.0.5
allow-newer: true
nix:
  packages: [zlib]
flags:
  aeson-pretty:
    lib-only: true
  # This is so we don't depend on libtinfo
  haskeline:
    terminfo: false
    examples: false
  cryptonite:
    use_target_attributes: false
